version: "3.0"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /Users/mac/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: .DockerFile
    links:
      - mongodb
    ports:
      - "3004:3004"
    volumes:
      - ./ :/home/node/app
    mem_limit: 200m
